name: Update nightly sources

on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 0 * * *" # repeat every day
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 

env:
  REPO_NAME: inochi-creator-nightly

jobs:
  release-check:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08

    steps:
      - uses: actions/checkout@v3

      - name: Fix git
        run: |
          git config --global --add safe.directory /__w/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}

      - name: Run creator update script
        run: |
          ./update-creator.sh 

      - name: Install deps
        run: |
          dnf -y install dub ldc python3-pyyaml

      - name: Update dependencies
        run: |
          ./update-dependencies.sh --nightly --ext-creator=latest-creator.yml

      - name: Commit changes
        id: is-updated 
        run: |
          git status -s -uno
          [ -z "$(git status -s -uno)" ] || echo "updated=true" >> $GITHUB_OUTPUT

      - name: Commit and push to branch
        if: steps.is-updated.outputs.updated
        run: |
          git config --global user.name 'Nightly Updater'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Automated update"
          git push origin HEAD:main
